### ISSUE TITLE
Dimension labels fall off

### ISSUE THREAD

**Issue by Galactico076** [mcgovey/D3-Bullet-Chart#22]
I'v installed the D3-bullet graph. When I create a graph with my own data the dimension labels "fall off" the left side of the object (see attachment). No matter how wide I make the object. Is there anything I can do?

![qv bullet graph](https://cloud.githubusercontent.com/assets/14836076/10099235/13dde20e-6388-11e5-81bc-be850dce0a9c.PNG)

**Comment by mcgovey** [comment]
Try using the dimension text space slider under Chart Configuration > Dimensions.  Hopefully this works, please let me know.

![image](https://cloud.githubusercontent.com/assets/1817579/10145502/7a909814-65f1-11e5-8411-80a996544bac.png)

**Comment by Galactico076** [comment]
Hi. It seems that your reply refers to Qlik Sense. I was talking about Qlikview. Sorry, I should've mentioned it explicitly.

**Comment by mcgovey** [comment]
This extension is for Qlik Sense.  It seems like the QlikView Bullet Chart you want is this one - https://github.com/stefanwalther/qvD3BulletCharts

**Comment by Galactico076** [comment]
Ok, you're probably right in closing this thread, but my problem remains. The Bullet Chart you're referring to is the one I'm using. So again: how can I get the labels to fit?

**Comment by mcgovey** [comment]
I am not entirely sure how you would have installed this extension in QlikView, since there is no qar file in the package and the files included are not cross compatible with QlikView. This has only been tested in Qlik Sense.  Would you mind sending me a screenshot of the qext file in the directory where you installed this?

**Comment by Galactico076** [comment]
![image](https://cloud.githubusercontent.com/assets/14836076/10166490/93bc325c-66c4-11e5-9588-d7d3ef403ebd.png)

this the QAR that I use

**Comment by mcgovey** [comment]
You are in the wrong repository.  If you look at the folder that you are in it is called "qvD3BulletCharts-master" which is the name of this repo https://github.com/stefanwalther/qvD3BulletCharts.  The package for this repository does not contain any qar files.
