### ISSUE TITLE
Add option to show up to 2 progress bars inside a dimension bar

### ISSUE THREAD

**Issue by katsafone** [mcgovey/D3-Bullet-Chart#24]
This would a fantastic extension for measuring project and strategic plan action performance.

The idea of the 2 progress bars one above the other within each dimension bar to show either a number within a user defined range or % complete would make this a very usable extension for the above purpose.

I'm looking at using the top progress bar for financial expenditure against budget and the bottom equivalent for % of the project completed at that time.

While I have plenty of experience in the SQL space I'm certainly not a developer when it comes to java language and CSS.

What are your thoughts here?

**Comment by mcgovey** [comment]
Would you mind putting together an image with an example of what you are looking to achieve? I'm having a tough time wrapping my head around what you're looking to do.  You can upload the image here [http://imgur.com/](http://imgur.com/) then paste the link in your reply.  Thank you!

**Comment by mcgovey** [comment]
No response. Closing Issue
